// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2020
// @generated from protobuf file "annotation.proto" (package "dp.service.annotation", syntax proto3)
// tslint:disable
//
//
// annotation.proto
//
// Contains RPC messages and interface specific to the Annotation Service.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { CalculationsSpec } from "./common";
import { EventMetadata } from "./common";
import { Attribute } from "./common";
import { DataColumn } from "./common";
import { DataTimestamps } from "./common";
import { ExceptionalResult } from "./common";
import { Timestamp } from "./common";
/**
 *
 * Mechanism for identifying a set of data within the archive.  This will be used to support other features
 * such as adding annotations to data sets or exporting data sets.
 *
 * A DataSet specifies archived data across multiple DataBlocks.  Each DataBlock specifies a time range and list of
 * data sources (columns/PVs).
 *
 *
 * @generated from protobuf message dp.service.annotation.DataSet
 */
export interface DataSet {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string ownerId = 3;
     */
    ownerId: string;
    /**
     * @generated from protobuf field: string description = 4;
     */
    description: string;
    /**
     * @generated from protobuf field: repeated dp.service.annotation.DataBlock dataBlocks = 5;
     */
    dataBlocks: DataBlock[];
}
/**
 * @generated from protobuf message dp.service.annotation.DataBlock
 */
export interface DataBlock {
    /**
     * @generated from protobuf field: Timestamp beginTime = 1;
     */
    beginTime?: Timestamp;
    /**
     * @generated from protobuf field: Timestamp endTime = 2;
     */
    endTime?: Timestamp;
    /**
     * @generated from protobuf field: repeated string pvNames = 3;
     */
    pvNames: string[];
}
/**
 *
 * Create DataSet Request.
 *
 * Contains a DataSet object to be created by the handler.  The dataSetId field in the supplied DataSet object is
 * ignored, the id will be generated by the service and returned in the corresponding CreateDataSetResult.
 *
 * @generated from protobuf message dp.service.annotation.CreateDataSetRequest
 */
export interface CreateDataSetRequest {
    /**
     * @generated from protobuf field: dp.service.annotation.DataSet dataSet = 1;
     */
    dataSet?: DataSet;
}
/**
 *
 * Create DataSet Response.
 *
 * Contains response to createDataSet() API request.  Message payload is exceptionalResult if request is rejected or an
 * error is encountered by the handler, otherwise contains a CreateDataSetResult.
 *
 * @generated from protobuf message dp.service.annotation.CreateDataSetResponse
 */
export interface CreateDataSetResponse {
    /**
     * @generated from protobuf field: Timestamp responseTime = 1;
     */
    responseTime?: Timestamp;
    /**
     * @generated from protobuf oneof: result
     */
    result: {
        oneofKind: "exceptionalResult";
        /**
         * @generated from protobuf field: ExceptionalResult exceptionalResult = 10;
         */
        exceptionalResult: ExceptionalResult;
    } | {
        oneofKind: "createDataSetResult";
        /**
         * @generated from protobuf field: dp.service.annotation.CreateDataSetResponse.CreateDataSetResult createDataSetResult = 11;
         */
        createDataSetResult: CreateDataSetResponse_CreateDataSetResult;
    } | {
        oneofKind: undefined;
    };
}
/**
 *
 * Successful Result.
 *
 * Contains the results of a successful request to create a DataSet, with the id of the newly created DataSet.
 *
 * @generated from protobuf message dp.service.annotation.CreateDataSetResponse.CreateDataSetResult
 */
export interface CreateDataSetResponse_CreateDataSetResult {
    /**
     * @generated from protobuf field: string dataSetId = 1;
     */
    dataSetId: string;
}
/**
 *
 * Query DataSet Request.
 *
 * Contains parameters for a query over existing DataSets.  A query includes a list of
 * (one or more) criteria. The criterion can be used individually or combined for compound queries.
 * E.g., a query request might use an OwnerCriterion and TextCriterion to find DataSets
 * for the specified owner matching containing the specified text.
 *
 * @generated from protobuf message dp.service.annotation.QueryDataSetsRequest
 */
export interface QueryDataSetsRequest {
    /**
     * @generated from protobuf field: repeated dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion criteria = 1;
     */
    criteria: QueryDataSetsRequest_QueryDataSetsCriterion[];
}
/**
 * @generated from protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion
 */
export interface QueryDataSetsRequest_QueryDataSetsCriterion {
    /**
     * @generated from protobuf oneof: criterion
     */
    criterion: {
        oneofKind: "idCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.IdCriterion idCriterion = 10;
         */
        idCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion;
    } | {
        oneofKind: "ownerCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.OwnerCriterion ownerCriterion = 11;
         */
        ownerCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion;
    } | {
        oneofKind: "textCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.TextCriterion textCriterion = 12;
         */
        textCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion;
    } | {
        oneofKind: "pvNameCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.PvNameCriterion pvNameCriterion = 13;
         */
        pvNameCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion;
    } | {
        oneofKind: undefined;
    };
}
/**
 *
 * Criterion used to search dataset id field.  "And" operator is used to combine with other criteria.
 *
 * @generated from protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.IdCriterion
 */
export interface QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
}
/**
 *
 * Criterion used to search dataset ownerId field.  "And" operator is used to combine with other criteria.
 *
 * @generated from protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.OwnerCriterion
 */
export interface QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion {
    /**
     * @generated from protobuf field: string ownerId = 1;
     */
    ownerId: string;
}
/**
 *
 * Criterion used to search dataset name and description fields.  "Or" operator is used to combine with other criteria.
 *
 * @generated from protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.TextCriterion
 */
export interface QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion {
    /**
     * @generated from protobuf field: string text = 1;
     */
    text: string;
}
/**
 *
 * Criterion used to search data blocks for the specified PV name.  "Or" operator is used to combine with other criteria.
 *
 * @generated from protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.PvNameCriterion
 */
export interface QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
}
/**
 *
 * Query DataSet Response.
 *
 * Contains the results of a DataSets query.  Payload is an ExceptionalResult if the request is invalid, an error is
 * encountered processing the query, or the query result is empty.  Otherwise payload is a DataSetsResult with a list
 * of DataSets matching the query parameters.
 *
 * @generated from protobuf message dp.service.annotation.QueryDataSetsResponse
 */
export interface QueryDataSetsResponse {
    /**
     * @generated from protobuf field: Timestamp responseTime = 1;
     */
    responseTime?: Timestamp;
    /**
     * @generated from protobuf oneof: result
     */
    result: {
        oneofKind: "exceptionalResult";
        /**
         * @generated from protobuf field: ExceptionalResult exceptionalResult = 10;
         */
        exceptionalResult: ExceptionalResult;
    } | {
        oneofKind: "dataSetsResult";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryDataSetsResponse.DataSetsResult dataSetsResult = 11;
         */
        dataSetsResult: QueryDataSetsResponse_DataSetsResult;
    } | {
        oneofKind: undefined;
    };
}
/**
 *
 * Datasets Query Result Content.
 *
 * Result contains a list of DataSet messages matching the query parameters.
 *
 * @generated from protobuf message dp.service.annotation.QueryDataSetsResponse.DataSetsResult
 */
export interface QueryDataSetsResponse_DataSetsResult {
    /**
     * @generated from protobuf field: repeated dp.service.annotation.DataSet dataSets = 1;
     */
    dataSets: DataSet[];
}
/**
 *
 * Calculations.
 *
 * Defines the data structure used for representing Calculations in both creating and querying Annotations.
 * To the extent possible, it parallels the data structures used in the ingestion of regular time-series data in order
 * that user-defined Calculations can be treated in a similar fashion for the purposes of querying and exporting data
 * that includes both PV data and user-defined Calculations.
 *
 * The Calculations object includes a list of CalculationsDataFrames.  Each CalculationsDataFrame includes
 * a name, a DataTimestamps object, and a list of DataColumns, each of which contains a vector of data values for a
 * single Calculation and specifies a DataValue for each timestamp specified by the corresponding DataTimestamps object.
 *
 * It might be helpful to use the analogy of an Excel workbook.  The Calculations object is the workbook, and each
 * CalculationDataFrame is a worksheet in that workbook that contains a column of timestamps and columns of calculated
 * data with a value for each timestamp.
 *
 * @generated from protobuf message dp.service.annotation.Calculations
 */
export interface Calculations {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: repeated dp.service.annotation.Calculations.CalculationsDataFrame calculationDataFrames = 2;
     */
    calculationDataFrames: Calculations_CalculationsDataFrame[];
}
/**
 * @generated from protobuf message dp.service.annotation.Calculations.CalculationsDataFrame
 */
export interface Calculations_CalculationsDataFrame {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: DataTimestamps dataTimestamps = 2;
     */
    dataTimestamps?: DataTimestamps;
    /**
     * @generated from protobuf field: repeated DataColumn dataColumns = 3;
     */
    dataColumns: DataColumn[];
}
/**
 *
 * CreateAnnotationRequest.
 *
 * A CreateAnnotationRequest message includes three required fields: ownerId (unique id of owner), dataSetIds (list of
 * unique ids of associated DataSets), and name (brief annotation name).  It includes several optional fields used
 * for linking to associated Annotations, adding descriptive information, associating with an event / experiment, and
 * attaching user-defined Calculations.
 *
 * The lists of associated DataSet ids and Annotation ids are an initial attempt to meet the requirement for tracking
 * data provenance.  To add Calculations that are derived from (or related to) regular PV time-series data in the
 * archive, the following steps are taken:
 *
 * - Create a DataSet that contains one or more Data Blocks that reference the PVs and time range(s) from the
 *   archive used in the calculation.
 * - Create an Annotation containing the unique id of that DataSet in the list of dataSetIds, and includes the desired
 *   Calculations.
 *
 * To add Calculations that are derived from other user-defined Calculations (that are part of another Annotation like
 * the one crated above), the following step is taken:
 *
 * - Create an Annotation containing the unique id of the Annotation that contains the original Calculations in the
 *   list of associated annotationIds, and includes the new Calculations derived from the original.
 *
 * @generated from protobuf message dp.service.annotation.CreateAnnotationRequest
 */
export interface CreateAnnotationRequest {
    /**
     * @generated from protobuf field: string ownerId = 1;
     */
    ownerId: string;
    /**
     * @generated from protobuf field: repeated string dataSetIds = 2;
     */
    dataSetIds: string[];
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: repeated string annotationIds = 4;
     */
    annotationIds: string[];
    /**
     * @generated from protobuf field: string comment = 5;
     */
    comment: string;
    /**
     * @generated from protobuf field: repeated string tags = 6;
     */
    tags: string[];
    /**
     * @generated from protobuf field: repeated Attribute attributes = 7;
     */
    attributes: Attribute[];
    /**
     * @generated from protobuf field: EventMetadata eventMetadata = 8;
     */
    eventMetadata?: EventMetadata;
    /**
     * @generated from protobuf field: dp.service.annotation.Calculations calculations = 9;
     */
    calculations?: Calculations;
}
/**
 *
 * Create Annotation Response.
 *
 * Contains details for response to request to add an annotation to a DataSet.  Response includes either
 * an ExceptionalResult describing a rejection or error situation, or a CreateAnnotationResult indicating the request
 * was handled successfully.
 *
 * @generated from protobuf message dp.service.annotation.CreateAnnotationResponse
 */
export interface CreateAnnotationResponse {
    /**
     * @generated from protobuf field: Timestamp responseTime = 1;
     */
    responseTime?: Timestamp;
    /**
     * @generated from protobuf oneof: result
     */
    result: {
        oneofKind: "exceptionalResult";
        /**
         * @generated from protobuf field: ExceptionalResult exceptionalResult = 10;
         */
        exceptionalResult: ExceptionalResult;
    } | {
        oneofKind: "createAnnotationResult";
        /**
         * @generated from protobuf field: dp.service.annotation.CreateAnnotationResponse.CreateAnnotationResult createAnnotationResult = 11;
         */
        createAnnotationResult: CreateAnnotationResponse_CreateAnnotationResult;
    } | {
        oneofKind: undefined;
    };
}
/**
 *
 * Successful Annotation Result.
 *
 * Contains the results of a successful request to add an annotation to a DataSet, including the id for the newly
 * created annotation.
 *
 * @generated from protobuf message dp.service.annotation.CreateAnnotationResponse.CreateAnnotationResult
 */
export interface CreateAnnotationResponse_CreateAnnotationResult {
    /**
     * @generated from protobuf field: string annotationId = 1;
     */
    annotationId: string;
}
/**
 *
 * Annotations Query Request.
 *
 * Contains a list of QueryAnnotationsCriterion for querying annotations. List can include a single criterion,
 * or multiple criteria for a compound query. E.g., a query request might use an OwnerCriterion and TextCriterion
 * to find annotations for the specified owner matching the text filter.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest
 */
export interface QueryAnnotationsRequest {
    /**
     * @generated from protobuf field: repeated dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion criteria = 1;
     */
    criteria: QueryAnnotationsRequest_QueryAnnotationsCriterion[];
}
/**
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion {
    /**
     * @generated from protobuf oneof: criterion
     */
    criterion: {
        oneofKind: "idCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.IdCriterion idCriterion = 10;
         */
        idCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion;
    } | {
        oneofKind: "ownerCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.OwnerCriterion ownerCriterion = 11;
         */
        ownerCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion;
    } | {
        oneofKind: "dataSetsCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.DataSetsCriterion dataSetsCriterion = 12;
         */
        dataSetsCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion;
    } | {
        oneofKind: "annotationsCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.AnnotationsCriterion annotationsCriterion = 13;
         */
        annotationsCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion;
    } | {
        oneofKind: "textCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.TextCriterion textCriterion = 14;
         */
        textCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion;
    } | {
        oneofKind: "tagsCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.TagsCriterion tagsCriterion = 15;
         */
        tagsCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion;
    } | {
        oneofKind: "attributesCriterion";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.AttributesCriterion attributesCriterion = 16;
         */
        attributesCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion;
    } | {
        oneofKind: undefined;
    };
}
/**
 *
 * Criterion used to query annotations by id.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.IdCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
}
/**
 *
 * Criterion used to query annotations by owner id.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.OwnerCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion {
    /**
     * @generated from protobuf field: string ownerId = 1;
     */
    ownerId: string;
}
/**
 *
 * Criterion used to query annotations by id of associated dataset.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.DataSetsCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion {
    /**
     * @generated from protobuf field: string dataSetId = 1;
     */
    dataSetId: string;
}
/**
 *
 * Criterion used to query annotations by id of associated annotation.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.AnnotationsCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion {
    /**
     * @generated from protobuf field: string annotationId = 1;
     */
    annotationId: string;
}
/**
 *
 * Criterion used to query annotations by text contained in the name, comment, and eventMetadata description fields.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.TextCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion {
    /**
     * @generated from protobuf field: string text = 1;
     */
    text: string;
}
/**
 *
 * Criterion used to query annotations by tag value.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.TagsCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion {
    /**
     * @generated from protobuf field: string tagValue = 1;
     */
    tagValue: string;
}
/**
 *
 * Criterion used to query annotations by attribute key and value.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.AttributesCriterion
 */
export interface QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion {
    /**
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * @generated from protobuf field: string value = 2;
     */
    value: string;
}
/**
 *
 * QueryAnnotationsResponse.
 *
 * Contains results from queryAnnotations() API request.  Message payload is either ExceptionalResult indicating
 * rejection, an error handling the request, or an empty query result, otherwise contains an AnnotationsResult with
 * an entry for each Annotation matching the query criteria.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsResponse
 */
export interface QueryAnnotationsResponse {
    /**
     * @generated from protobuf field: Timestamp responseTime = 1;
     */
    responseTime?: Timestamp;
    /**
     * @generated from protobuf oneof: result
     */
    result: {
        oneofKind: "exceptionalResult";
        /**
         * @generated from protobuf field: ExceptionalResult exceptionalResult = 10;
         */
        exceptionalResult: ExceptionalResult;
    } | {
        oneofKind: "annotationsResult";
        /**
         * @generated from protobuf field: dp.service.annotation.QueryAnnotationsResponse.AnnotationsResult annotationsResult = 11;
         */
        annotationsResult: QueryAnnotationsResponse_AnnotationsResult;
    } | {
        oneofKind: undefined;
    };
}
/**
 *
 * Annotations Query Result Content.
 *
 * Result contains a list of Annotation messages, one for each annotation matching the query criteria.
 *
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsResponse.AnnotationsResult
 */
export interface QueryAnnotationsResponse_AnnotationsResult {
    /**
     * @generated from protobuf field: repeated dp.service.annotation.QueryAnnotationsResponse.AnnotationsResult.Annotation annotations = 1;
     */
    annotations: QueryAnnotationsResponse_AnnotationsResult_Annotation[];
}
/**
 * @generated from protobuf message dp.service.annotation.QueryAnnotationsResponse.AnnotationsResult.Annotation
 */
export interface QueryAnnotationsResponse_AnnotationsResult_Annotation {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string ownerId = 2;
     */
    ownerId: string;
    /**
     * @generated from protobuf field: repeated string dataSetIds = 3;
     */
    dataSetIds: string[];
    /**
     * @generated from protobuf field: repeated dp.service.annotation.DataSet dataSets = 4;
     */
    dataSets: DataSet[];
    /**
     * @generated from protobuf field: string name = 5;
     */
    name: string;
    /**
     * @generated from protobuf field: repeated string annotationIds = 6;
     */
    annotationIds: string[];
    /**
     * @generated from protobuf field: string comment = 7;
     */
    comment: string;
    /**
     * @generated from protobuf field: repeated string tags = 8;
     */
    tags: string[];
    /**
     * @generated from protobuf field: repeated Attribute attributes = 9;
     */
    attributes: Attribute[];
    /**
     * @generated from protobuf field: EventMetadata eventMetadata = 10;
     */
    eventMetadata?: EventMetadata;
    /**
     * @generated from protobuf field: dp.service.annotation.Calculations calculations = 11;
     */
    calculations?: Calculations;
}
/**
 *
 * ExportDataRequest
 *
 * Used as parameter to the exportData() method.  Includes fields for specifying the id of the DataSet or
 * Calculations object to be exported, and an enum for specifying output format.  Both datasetId and calculationsSpec
 * are optional, but one or the other must be specified.
 *
 * @generated from protobuf message dp.service.annotation.ExportDataRequest
 */
export interface ExportDataRequest {
    /**
     * @generated from protobuf field: string dataSetId = 1;
     */
    dataSetId: string;
    /**
     * @generated from protobuf field: CalculationsSpec calculationsSpec = 2;
     */
    calculationsSpec?: CalculationsSpec;
    /**
     * @generated from protobuf field: dp.service.annotation.ExportDataRequest.ExportOutputFormat outputFormat = 3;
     */
    outputFormat: ExportDataRequest_ExportOutputFormat;
}
/**
 * @generated from protobuf enum dp.service.annotation.ExportDataRequest.ExportOutputFormat
 */
export declare enum ExportDataRequest_ExportOutputFormat {
    /**
     * Indicates no enum value has been specified, and the request will be rejected.
     *
     * @generated from protobuf enum value: EXPORT_FORMAT_UNSPECIFIED = 0;
     */
    EXPORT_FORMAT_UNSPECIFIED = 0,
    /**
     * HDF5 file containing bucketed data for multiple PVs.
     *
     * @generated from protobuf enum value: EXPORT_FORMAT_HDF5 = 1;
     */
    EXPORT_FORMAT_HDF5 = 1,
    /**
     * Tabular comma-separated values format.
     *
     * @generated from protobuf enum value: EXPORT_FORMAT_CSV = 2;
     */
    EXPORT_FORMAT_CSV = 2,
    /**
     * Tabular Excel format.
     *
     * @generated from protobuf enum value: EXPORT_FORMAT_XLSX = 3;
     */
    EXPORT_FORMAT_XLSX = 3
}
/**
 *
 * ExportDataResponse
 *
 * Used as response from the exportData() method.  Payload includes either an ExceptionalResult indicating a problem
 * in handling the export request, or an ExportDataResult for a successful request.
 *
 * ExportDataResult includes fields specifying the full path for the export output file and
 * (optionally if configured) the URL for accessing the file via a web server.
 *
 * @generated from protobuf message dp.service.annotation.ExportDataResponse
 */
export interface ExportDataResponse {
    /**
     * @generated from protobuf field: Timestamp responseTime = 1;
     */
    responseTime?: Timestamp;
    /**
     * @generated from protobuf oneof: result
     */
    result: {
        oneofKind: "exceptionalResult";
        /**
         * @generated from protobuf field: ExceptionalResult exceptionalResult = 10;
         */
        exceptionalResult: ExceptionalResult;
    } | {
        oneofKind: "exportDataResult";
        /**
         * @generated from protobuf field: dp.service.annotation.ExportDataResponse.ExportDataResult exportDataResult = 11;
         */
        exportDataResult: ExportDataResponse_ExportDataResult;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message dp.service.annotation.ExportDataResponse.ExportDataResult
 */
export interface ExportDataResponse_ExportDataResult {
    /**
     * @generated from protobuf field: string filePath = 1;
     */
    filePath: string;
    /**
     * @generated from protobuf field: string fileUrl = 2;
     */
    fileUrl: string;
}
declare class DataSet$Type extends MessageType<DataSet> {
    constructor();
    create(value?: PartialMessage<DataSet>): DataSet;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DataSet): DataSet;
    internalBinaryWrite(message: DataSet, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.DataSet
 */
export declare const DataSet: DataSet$Type;
declare class DataBlock$Type extends MessageType<DataBlock> {
    constructor();
    create(value?: PartialMessage<DataBlock>): DataBlock;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DataBlock): DataBlock;
    internalBinaryWrite(message: DataBlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.DataBlock
 */
export declare const DataBlock: DataBlock$Type;
declare class CreateDataSetRequest$Type extends MessageType<CreateDataSetRequest> {
    constructor();
    create(value?: PartialMessage<CreateDataSetRequest>): CreateDataSetRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateDataSetRequest): CreateDataSetRequest;
    internalBinaryWrite(message: CreateDataSetRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.CreateDataSetRequest
 */
export declare const CreateDataSetRequest: CreateDataSetRequest$Type;
declare class CreateDataSetResponse$Type extends MessageType<CreateDataSetResponse> {
    constructor();
    create(value?: PartialMessage<CreateDataSetResponse>): CreateDataSetResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateDataSetResponse): CreateDataSetResponse;
    internalBinaryWrite(message: CreateDataSetResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.CreateDataSetResponse
 */
export declare const CreateDataSetResponse: CreateDataSetResponse$Type;
declare class CreateDataSetResponse_CreateDataSetResult$Type extends MessageType<CreateDataSetResponse_CreateDataSetResult> {
    constructor();
    create(value?: PartialMessage<CreateDataSetResponse_CreateDataSetResult>): CreateDataSetResponse_CreateDataSetResult;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateDataSetResponse_CreateDataSetResult): CreateDataSetResponse_CreateDataSetResult;
    internalBinaryWrite(message: CreateDataSetResponse_CreateDataSetResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.CreateDataSetResponse.CreateDataSetResult
 */
export declare const CreateDataSetResponse_CreateDataSetResult: CreateDataSetResponse_CreateDataSetResult$Type;
declare class QueryDataSetsRequest$Type extends MessageType<QueryDataSetsRequest> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsRequest>): QueryDataSetsRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsRequest): QueryDataSetsRequest;
    internalBinaryWrite(message: QueryDataSetsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsRequest
 */
export declare const QueryDataSetsRequest: QueryDataSetsRequest$Type;
declare class QueryDataSetsRequest_QueryDataSetsCriterion$Type extends MessageType<QueryDataSetsRequest_QueryDataSetsCriterion> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsRequest_QueryDataSetsCriterion>): QueryDataSetsRequest_QueryDataSetsCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsRequest_QueryDataSetsCriterion): QueryDataSetsRequest_QueryDataSetsCriterion;
    internalBinaryWrite(message: QueryDataSetsRequest_QueryDataSetsCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion
 */
export declare const QueryDataSetsRequest_QueryDataSetsCriterion: QueryDataSetsRequest_QueryDataSetsCriterion$Type;
declare class QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion$Type extends MessageType<QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion>): QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion): QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion;
    internalBinaryWrite(message: QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.IdCriterion
 */
export declare const QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_IdCriterion$Type;
declare class QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion$Type extends MessageType<QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion>): QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion): QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion;
    internalBinaryWrite(message: QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.OwnerCriterion
 */
export declare const QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_OwnerCriterion$Type;
declare class QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion$Type extends MessageType<QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion>): QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion): QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion;
    internalBinaryWrite(message: QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.TextCriterion
 */
export declare const QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_TextCriterion$Type;
declare class QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion$Type extends MessageType<QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion>): QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion): QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion;
    internalBinaryWrite(message: QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsRequest.QueryDataSetsCriterion.PvNameCriterion
 */
export declare const QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion: QueryDataSetsRequest_QueryDataSetsCriterion_PvNameCriterion$Type;
declare class QueryDataSetsResponse$Type extends MessageType<QueryDataSetsResponse> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsResponse>): QueryDataSetsResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsResponse): QueryDataSetsResponse;
    internalBinaryWrite(message: QueryDataSetsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsResponse
 */
export declare const QueryDataSetsResponse: QueryDataSetsResponse$Type;
declare class QueryDataSetsResponse_DataSetsResult$Type extends MessageType<QueryDataSetsResponse_DataSetsResult> {
    constructor();
    create(value?: PartialMessage<QueryDataSetsResponse_DataSetsResult>): QueryDataSetsResponse_DataSetsResult;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryDataSetsResponse_DataSetsResult): QueryDataSetsResponse_DataSetsResult;
    internalBinaryWrite(message: QueryDataSetsResponse_DataSetsResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryDataSetsResponse.DataSetsResult
 */
export declare const QueryDataSetsResponse_DataSetsResult: QueryDataSetsResponse_DataSetsResult$Type;
declare class Calculations$Type extends MessageType<Calculations> {
    constructor();
    create(value?: PartialMessage<Calculations>): Calculations;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Calculations): Calculations;
    internalBinaryWrite(message: Calculations, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.Calculations
 */
export declare const Calculations: Calculations$Type;
declare class Calculations_CalculationsDataFrame$Type extends MessageType<Calculations_CalculationsDataFrame> {
    constructor();
    create(value?: PartialMessage<Calculations_CalculationsDataFrame>): Calculations_CalculationsDataFrame;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Calculations_CalculationsDataFrame): Calculations_CalculationsDataFrame;
    internalBinaryWrite(message: Calculations_CalculationsDataFrame, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.Calculations.CalculationsDataFrame
 */
export declare const Calculations_CalculationsDataFrame: Calculations_CalculationsDataFrame$Type;
declare class CreateAnnotationRequest$Type extends MessageType<CreateAnnotationRequest> {
    constructor();
    create(value?: PartialMessage<CreateAnnotationRequest>): CreateAnnotationRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateAnnotationRequest): CreateAnnotationRequest;
    internalBinaryWrite(message: CreateAnnotationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.CreateAnnotationRequest
 */
export declare const CreateAnnotationRequest: CreateAnnotationRequest$Type;
declare class CreateAnnotationResponse$Type extends MessageType<CreateAnnotationResponse> {
    constructor();
    create(value?: PartialMessage<CreateAnnotationResponse>): CreateAnnotationResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateAnnotationResponse): CreateAnnotationResponse;
    internalBinaryWrite(message: CreateAnnotationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.CreateAnnotationResponse
 */
export declare const CreateAnnotationResponse: CreateAnnotationResponse$Type;
declare class CreateAnnotationResponse_CreateAnnotationResult$Type extends MessageType<CreateAnnotationResponse_CreateAnnotationResult> {
    constructor();
    create(value?: PartialMessage<CreateAnnotationResponse_CreateAnnotationResult>): CreateAnnotationResponse_CreateAnnotationResult;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateAnnotationResponse_CreateAnnotationResult): CreateAnnotationResponse_CreateAnnotationResult;
    internalBinaryWrite(message: CreateAnnotationResponse_CreateAnnotationResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.CreateAnnotationResponse.CreateAnnotationResult
 */
export declare const CreateAnnotationResponse_CreateAnnotationResult: CreateAnnotationResponse_CreateAnnotationResult$Type;
declare class QueryAnnotationsRequest$Type extends MessageType<QueryAnnotationsRequest> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest>): QueryAnnotationsRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest): QueryAnnotationsRequest;
    internalBinaryWrite(message: QueryAnnotationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest
 */
export declare const QueryAnnotationsRequest: QueryAnnotationsRequest$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.IdCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_IdCriterion$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.OwnerCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_OwnerCriterion$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.DataSetsCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_DataSetsCriterion$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.AnnotationsCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_AnnotationsCriterion$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.TextCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_TextCriterion$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.TagsCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_TagsCriterion$Type;
declare class QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion$Type extends MessageType<QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion>): QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion): QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion;
    internalBinaryWrite(message: QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsRequest.QueryAnnotationsCriterion.AttributesCriterion
 */
export declare const QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion: QueryAnnotationsRequest_QueryAnnotationsCriterion_AttributesCriterion$Type;
declare class QueryAnnotationsResponse$Type extends MessageType<QueryAnnotationsResponse> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsResponse>): QueryAnnotationsResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsResponse): QueryAnnotationsResponse;
    internalBinaryWrite(message: QueryAnnotationsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsResponse
 */
export declare const QueryAnnotationsResponse: QueryAnnotationsResponse$Type;
declare class QueryAnnotationsResponse_AnnotationsResult$Type extends MessageType<QueryAnnotationsResponse_AnnotationsResult> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsResponse_AnnotationsResult>): QueryAnnotationsResponse_AnnotationsResult;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsResponse_AnnotationsResult): QueryAnnotationsResponse_AnnotationsResult;
    internalBinaryWrite(message: QueryAnnotationsResponse_AnnotationsResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsResponse.AnnotationsResult
 */
export declare const QueryAnnotationsResponse_AnnotationsResult: QueryAnnotationsResponse_AnnotationsResult$Type;
declare class QueryAnnotationsResponse_AnnotationsResult_Annotation$Type extends MessageType<QueryAnnotationsResponse_AnnotationsResult_Annotation> {
    constructor();
    create(value?: PartialMessage<QueryAnnotationsResponse_AnnotationsResult_Annotation>): QueryAnnotationsResponse_AnnotationsResult_Annotation;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryAnnotationsResponse_AnnotationsResult_Annotation): QueryAnnotationsResponse_AnnotationsResult_Annotation;
    internalBinaryWrite(message: QueryAnnotationsResponse_AnnotationsResult_Annotation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.QueryAnnotationsResponse.AnnotationsResult.Annotation
 */
export declare const QueryAnnotationsResponse_AnnotationsResult_Annotation: QueryAnnotationsResponse_AnnotationsResult_Annotation$Type;
declare class ExportDataRequest$Type extends MessageType<ExportDataRequest> {
    constructor();
    create(value?: PartialMessage<ExportDataRequest>): ExportDataRequest;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExportDataRequest): ExportDataRequest;
    internalBinaryWrite(message: ExportDataRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.ExportDataRequest
 */
export declare const ExportDataRequest: ExportDataRequest$Type;
declare class ExportDataResponse$Type extends MessageType<ExportDataResponse> {
    constructor();
    create(value?: PartialMessage<ExportDataResponse>): ExportDataResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExportDataResponse): ExportDataResponse;
    internalBinaryWrite(message: ExportDataResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.ExportDataResponse
 */
export declare const ExportDataResponse: ExportDataResponse$Type;
declare class ExportDataResponse_ExportDataResult$Type extends MessageType<ExportDataResponse_ExportDataResult> {
    constructor();
    create(value?: PartialMessage<ExportDataResponse_ExportDataResult>): ExportDataResponse_ExportDataResult;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExportDataResponse_ExportDataResult): ExportDataResponse_ExportDataResult;
    internalBinaryWrite(message: ExportDataResponse_ExportDataResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message dp.service.annotation.ExportDataResponse.ExportDataResult
 */
export declare const ExportDataResponse_ExportDataResult: ExportDataResponse_ExportDataResult$Type;
/**
 * @generated ServiceType for protobuf service dp.service.annotation.DpAnnotationService
 */
export declare const DpAnnotationService: any;
export {};
