// @generated by protobuf-ts 2.9.3 with parameter output_javascript_es2020
// @generated from protobuf file "annotation.proto" (package "dp.service.annotation", syntax proto3)
// tslint:disable
//
//
// annotation.proto
//
// Contains RPC messages and interface specific to the Annotation Service.
//
// since: February, 2024
// version: 1.3.0
//
//
import { DpAnnotationService } from "./annotation";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
// 
// ------------------- RPC Interfaces ---------------------------
// 
/**
 *
 * Annotation Service Interface
 *
 * Interface for annotating archived data.  Registered annotation authors can create and modify data
 * annotations.
 *
 * @generated from protobuf service dp.service.annotation.DpAnnotationService
 */
export class DpAnnotationServiceClient {
    constructor(_transport) {
        this._transport = _transport;
        this.typeName = DpAnnotationService.typeName;
        this.methods = DpAnnotationService.methods;
        this.options = DpAnnotationService.options;
    }
    /**
     *
     * createComment: Add a comment annotation to a DataSet.
     *
     * This RPC sends a request to the annotation service to create an annotation with the specified parameters.
     * The annotation service performs validation, and for a valid request, attempts to create the annotation.
     * The response may indicate rejection, an error in handling the request, or successful handling of the request.
     * See CreateAnnotationResponse for more details.
     *
     * @generated from protobuf rpc: createAnnotation(dp.service.annotation.CreateAnnotationRequest) returns (dp.service.annotation.CreateAnnotationResponse);
     */
    createAnnotation(input, options) {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
}
